databases:
  - name: infotech-db
    plan: free

services:
  # 1. Servicio Web para el Backend (Django)
  - type: web
    name: infotech-backend
    plan: free
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: infotech-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: SEED_DB
        value: "True"
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: infotech-frontend
          property: host

  # 2. Sitio Estático para el Frontend (React + Vite)
  - type: web
    name: infotech-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: infotech-backend
          property: host
