# Generated by Django 5.2.14 on 2026-05-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('gestor', 'Gestor'), ('usuario', 'Usuario')], default='usuario', max_length=20, verbose_name='Rol'),
        ),
    ]
